// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: retrieve.proto

// Protobuf Java Version: 3.25.3
package edu.njucm.retrievejava.rpc;

/**
 * Protobuf type {@code retrieve.DoubleArrayResponse}
 */
public final class DoubleArrayResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:retrieve.DoubleArrayResponse)
    DoubleArrayResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DoubleArrayResponse.newBuilder() to construct.
  private DoubleArrayResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoubleArrayResponse() {
    resultArray_ = emptyDoubleList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DoubleArrayResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.njucm.retrievejava.rpc.RetrieveProto.internal_static_retrieve_DoubleArrayResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.njucm.retrievejava.rpc.RetrieveProto.internal_static_retrieve_DoubleArrayResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.njucm.retrievejava.rpc.DoubleArrayResponse.class, edu.njucm.retrievejava.rpc.DoubleArrayResponse.Builder.class);
  }

  public static final int RESULT_ARRAY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList resultArray_ =
      emptyDoubleList();
  /**
   * <code>repeated double result_array = 1;</code>
   * @return A list containing the resultArray.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getResultArrayList() {
    return resultArray_;
  }
  /**
   * <code>repeated double result_array = 1;</code>
   * @return The count of resultArray.
   */
  public int getResultArrayCount() {
    return resultArray_.size();
  }
  /**
   * <code>repeated double result_array = 1;</code>
   * @param index The index of the element to return.
   * @return The resultArray at the given index.
   */
  public double getResultArray(int index) {
    return resultArray_.getDouble(index);
  }
  private int resultArrayMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getResultArrayList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(resultArrayMemoizedSerializedSize);
    }
    for (int i = 0; i < resultArray_.size(); i++) {
      output.writeDoubleNoTag(resultArray_.getDouble(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 8 * getResultArrayList().size();
      size += dataSize;
      if (!getResultArrayList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      resultArrayMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.njucm.retrievejava.rpc.DoubleArrayResponse)) {
      return super.equals(obj);
    }
    edu.njucm.retrievejava.rpc.DoubleArrayResponse other = (edu.njucm.retrievejava.rpc.DoubleArrayResponse) obj;

    if (!getResultArrayList()
        .equals(other.getResultArrayList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultArrayCount() > 0) {
      hash = (37 * hash) + RESULT_ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getResultArrayList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.njucm.retrievejava.rpc.DoubleArrayResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code retrieve.DoubleArrayResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:retrieve.DoubleArrayResponse)
      edu.njucm.retrievejava.rpc.DoubleArrayResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.njucm.retrievejava.rpc.RetrieveProto.internal_static_retrieve_DoubleArrayResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.njucm.retrievejava.rpc.RetrieveProto.internal_static_retrieve_DoubleArrayResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.njucm.retrievejava.rpc.DoubleArrayResponse.class, edu.njucm.retrievejava.rpc.DoubleArrayResponse.Builder.class);
    }

    // Construct using edu.njucm.retrievejava.rpc.DoubleArrayResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resultArray_ = emptyDoubleList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.njucm.retrievejava.rpc.RetrieveProto.internal_static_retrieve_DoubleArrayResponse_descriptor;
    }

    @java.lang.Override
    public edu.njucm.retrievejava.rpc.DoubleArrayResponse getDefaultInstanceForType() {
      return edu.njucm.retrievejava.rpc.DoubleArrayResponse.getDefaultInstance();
    }

    @java.lang.Override
    public edu.njucm.retrievejava.rpc.DoubleArrayResponse build() {
      edu.njucm.retrievejava.rpc.DoubleArrayResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.njucm.retrievejava.rpc.DoubleArrayResponse buildPartial() {
      edu.njucm.retrievejava.rpc.DoubleArrayResponse result = new edu.njucm.retrievejava.rpc.DoubleArrayResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(edu.njucm.retrievejava.rpc.DoubleArrayResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        resultArray_.makeImmutable();
        result.resultArray_ = resultArray_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.njucm.retrievejava.rpc.DoubleArrayResponse) {
        return mergeFrom((edu.njucm.retrievejava.rpc.DoubleArrayResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.njucm.retrievejava.rpc.DoubleArrayResponse other) {
      if (other == edu.njucm.retrievejava.rpc.DoubleArrayResponse.getDefaultInstance()) return this;
      if (!other.resultArray_.isEmpty()) {
        if (resultArray_.isEmpty()) {
          resultArray_ = other.resultArray_;
          resultArray_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureResultArrayIsMutable();
          resultArray_.addAll(other.resultArray_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              double v = input.readDouble();
              ensureResultArrayIsMutable();
              resultArray_.addDouble(v);
              break;
            } // case 9
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureResultArrayIsMutable(alloc / 8);
              while (input.getBytesUntilLimit() > 0) {
                resultArray_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.DoubleList resultArray_ = emptyDoubleList();
    private void ensureResultArrayIsMutable() {
      if (!resultArray_.isModifiable()) {
        resultArray_ = makeMutableCopy(resultArray_);
      }
      bitField0_ |= 0x00000001;
    }
    private void ensureResultArrayIsMutable(int capacity) {
      if (!resultArray_.isModifiable()) {
        resultArray_ = makeMutableCopy(resultArray_, capacity);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated double result_array = 1;</code>
     * @return A list containing the resultArray.
     */
    public java.util.List<java.lang.Double>
        getResultArrayList() {
      resultArray_.makeImmutable();
      return resultArray_;
    }
    /**
     * <code>repeated double result_array = 1;</code>
     * @return The count of resultArray.
     */
    public int getResultArrayCount() {
      return resultArray_.size();
    }
    /**
     * <code>repeated double result_array = 1;</code>
     * @param index The index of the element to return.
     * @return The resultArray at the given index.
     */
    public double getResultArray(int index) {
      return resultArray_.getDouble(index);
    }
    /**
     * <code>repeated double result_array = 1;</code>
     * @param index The index to set the value at.
     * @param value The resultArray to set.
     * @return This builder for chaining.
     */
    public Builder setResultArray(
        int index, double value) {

      ensureResultArrayIsMutable();
      resultArray_.setDouble(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double result_array = 1;</code>
     * @param value The resultArray to add.
     * @return This builder for chaining.
     */
    public Builder addResultArray(double value) {

      ensureResultArrayIsMutable();
      resultArray_.addDouble(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double result_array = 1;</code>
     * @param values The resultArray to add.
     * @return This builder for chaining.
     */
    public Builder addAllResultArray(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureResultArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, resultArray_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double result_array = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultArray() {
      resultArray_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:retrieve.DoubleArrayResponse)
  }

  // @@protoc_insertion_point(class_scope:retrieve.DoubleArrayResponse)
  private static final edu.njucm.retrievejava.rpc.DoubleArrayResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.njucm.retrievejava.rpc.DoubleArrayResponse();
  }

  public static edu.njucm.retrievejava.rpc.DoubleArrayResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DoubleArrayResponse>
      PARSER = new com.google.protobuf.AbstractParser<DoubleArrayResponse>() {
    @java.lang.Override
    public DoubleArrayResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DoubleArrayResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoubleArrayResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.njucm.retrievejava.rpc.DoubleArrayResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

