// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: retrieve.proto

// Protobuf Java Version: 3.25.3
package edu.njucm.retrievejava.rpc;

public interface DoubleArrayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:retrieve.DoubleArrayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double result_array = 1;</code>
   * @return A list containing the resultArray.
   */
  java.util.List<java.lang.Double> getResultArrayList();
  /**
   * <code>repeated double result_array = 1;</code>
   * @return The count of resultArray.
   */
  int getResultArrayCount();
  /**
   * <code>repeated double result_array = 1;</code>
   * @param index The index of the element to return.
   * @return The resultArray at the given index.
   */
  double getResultArray(int index);
}
