// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: retrieve.proto

// Protobuf Java Version: 3.25.3
package edu.njucm.retrievejava.rpc;

public final class RetrieveProto {
  private RetrieveProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_retrieve_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_retrieve_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_retrieve_DoubleArrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_retrieve_DoubleArrayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016retrieve.proto\022\010retrieve\"%\n\rStringRequ" +
      "est\022\024\n\014input_string\030\001 \001(\t\"+\n\023DoubleArray" +
      "Response\022\024\n\014result_array\030\001 \003(\0012]\n\022Word2V" +
      "ectorService\022G\n\rprocessString\022\027.retrieve" +
      ".StringRequest\032\035.retrieve.DoubleArrayRes" +
      "ponseB-\n\032edu.njucm.retrievejava.rpcB\rRet" +
      "rieveProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_retrieve_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_retrieve_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_retrieve_StringRequest_descriptor,
        new java.lang.String[] { "InputString", });
    internal_static_retrieve_DoubleArrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_retrieve_DoubleArrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_retrieve_DoubleArrayResponse_descriptor,
        new java.lang.String[] { "ResultArray", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
