// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: retrieve.proto

// Protobuf Java Version: 3.25.3
package edu.njucm.retrievejava.rpc;

public interface StringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:retrieve.StringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input_string = 1;</code>
   * @return The inputString.
   */
  java.lang.String getInputString();
  /**
   * <code>string input_string = 1;</code>
   * @return The bytes for inputString.
   */
  com.google.protobuf.ByteString
      getInputStringBytes();
}
