#################################################
## mysql serverId , v1.0.26+ will autoGen
# canal.instance.mysql.slaveId=0

# position info
canal.instance.master.address=mysql:3306
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal123456
canal.instance.defaultDatabaseName=retrieve_new
canal.instance.connectionCharset=UTF-8
canal.instance.tsdb.enable=true

canal.instance.filter.regex=retrieve_new\.paper,retrieve_new\.paragraph
canal.instance.filter.black.regex=

canal.mq.topic=canal
canal.mq.partition=0
